// Generated by lazyqmk
// Layout: Test Layout
// Generated: <timestamp>

#pragma once

// Add keymap-specific configuration here

// Idle Effect Configuration
#define LQMK_IDLE_TIMEOUT_MS 60000
#define LQMK_IDLE_EFFECT_DURATION_MS 300000
#define LQMK_IDLE_EFFECT_MODE RGB_MATRIX_BREATHING

// Default to TUI layer-aware RGB colors when available
#ifdef RGB_MATRIX_ENABLE
#    undef RGB_MATRIX_DEFAULT_MODE
#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TUI_LAYER_COLORS
#    define LAYER_BASE_COLORS_LAYER_COUNT 2
#endif